version: '3'

services:
    rabbit-1:
        image: rabbitmq:3.10.5-management-alpine
        hostname: rabbit-1
        container_name: rabbit-1
        ports:
            - '8080:15672'
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

networks:
    gomc-broker:
