FROM golang:1.18-alpine AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build -o ./app


FROM alpine AS runtime

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk*

WORKDIR /app

COPY .env .
COPY --from=build /app/app .


CMD [ "./app" ]
